#spring.application.name=TimeOut

#time out
#resilience4j.timelimiter.instances.weatherForecastLimiter.timeoutDuration=2s
#resilience4j.timelimiter.instances.weatherForecastLimiter.cancelRunningFuture=true

#Retry
#resilience4j.retry.instances.getWeatherRetry.max-attempts=5
#resilience4j.retry.instances.getWeatherRetry.wait-duration=3s
#resilience4j.retry.instances.getWeatherRetry.retry-exceptions=java.io.IOException,org.springframework.web.client.HttpServerErrorException



#api rate Limter
##Fixed Window Rate Limiter Configuration
#[00:00 - 00:10] -> Allow 5 calls
#[00:10 - 00:20] -> Allow next 5 calls
#[00:20 - 00:30] -> Allow next 5 calls
#resilience4j.ratelimiter.instances.getRateLimiter.limitForPeriod=2
#resilience4j.ratelimiter.instances.getRateLimiter.limitRefreshPeriod=10s
#resilience4j.ratelimiter.instances.getRateLimiter.timeoutDuration=5s
#
#resilience4j.ratelimiter.instances.getMorWeathereRateLimiter.limitForPeriod=5
#resilience4j.ratelimiter.instances.getMorWeathereRateLimiter.limitRefreshPeriod=10s
#resilience4j.ratelimiter.instances.getMorWeathereRateLimiterr.timeoutDuration=5s








spring.application.name=circuit-breaker
# === Actuator Endpoints ===
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# === Circuit Breaker Configuration for 'externalApiCB' ===
resilience4j.circuitbreaker.instances.getWeatherCircuitbreaker.register-health-indicator=true
resilience4j.circuitbreaker.instances.getWeatherCircuitbreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.getWeatherCircuitbreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.getWeatherCircuitbreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.getWeatherCircuitbreaker.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.getWeatherCircuitbreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.getWeatherCircuitbreaker.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.getWeatherCircuitbreaker.slow-call-rate-threshold=100
resilience4j.circuitbreaker.instances.getWeatherCircuitbreaker.slow-call-duration-threshold=2s
