spring.application.name=Project
spring.datasource.url=jdbc:mysql://localhost:3306/transactionaldb
spring.datasource.username=root
spring.datasource.password=Yash@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver